version: '3'
services:
        compvis:
          image: jupyter/datascience-notebook:latest
          container_name: 'compvis'
          extra_hosts:
            - "host.docker.internal:host-gateway" 
          volumes:
            - ./:/home/jovyan/work
          ports:
            - 8888:8888
